name: Simple CI Pipeline

# Ce pipeline se lance Ã  chaque push ou pull request
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  hello-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Message de test
        run: echo "âœ… Hello CI ! Le pipeline fonctionne ðŸŽ‰"
