name: Simple CI Pipeline

# Le pipeline se lance Ã  chaque push ou pull request
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  hello-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Message de test
        run: echo "âœ… Hello CI ! Le pipeline fonctionne ðŸŽ‰"

  test-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # ou 20 selon ton projet

      - name: Installer les dÃ©pendances
        run: npm install

      - name: Lancer les tests unitaires
        run: npm test
